// components/markets/coinDescriptions.ts
// ── ORIGINAL 2–3 SENTENCE DESCRIPTIONS FOR EACH TIER-1 COIN ──

export const coinDescriptions: Record<string, string> = {
  BTC: 'Bitcoin is the first decentralized digital currency, launched in 2009 by the pseudonymous Satoshi Nakamoto. It operates on a peer-to-peer network without a central authority, using proof-of-work to secure transactions. Bitcoin is widely regarded as digital gold and a store of value.',
  ETH: 'Ethereum is a decentralized blockchain platform that enables smart contracts and decentralized applications (dApps) to run without downtime or third-party interference. Its native token, Ether, powers transactions and computational services on the network. Ethereum transitioned to proof-of-stake in 2022, dramatically reducing its energy consumption.',
  USDT: 'Tether (USDT) is the largest stablecoin by market cap, designed to maintain a 1:1 peg with the US dollar through reserve backing. It serves as the primary on-ramp, trading pair, and safe-haven asset across virtually every crypto exchange.',
  BNB: 'BNB is the native token of the BNB Chain ecosystem, originally launched by Binance to offer trading fee discounts. It now powers smart contracts on BNB Smart Chain, a high-throughput EVM-compatible network popular for DeFi and gaming applications.',
  SOL: 'Solana is a high-performance layer-1 blockchain designed for speed and low transaction costs, using a unique proof-of-history consensus mechanism alongside proof-of-stake. It supports thousands of transactions per second, making it popular for DeFi, NFTs, and meme-coin trading.',
  XRP: 'XRP is the native digital asset of the XRP Ledger, a fast and energy-efficient blockchain built for payments and cross-border settlement. Ripple, the company behind much of the XRP ecosystem, uses it to facilitate near-instant international transfers.',
  ADA: 'Cardano is a proof-of-stake blockchain platform founded by Ethereum co-creator Charles Hoskinson, emphasizing peer-reviewed research and formal verification. Its native token, ADA, is used for staking, governance, and transaction fees on the network.',
  DOGE: 'Dogecoin started as a lighthearted meme coin featuring the Shiba Inu dog, but grew into a widely recognized cryptocurrency with a passionate community. It uses a proof-of-work algorithm and is often used for tipping and micro-transactions.',
  TRX: 'TRON is a blockchain-based operating system focused on decentralizing content distribution and entertainment. Its native token, TRX, powers transactions, staking, and governance across the TRON ecosystem, which hosts one of the largest supplies of USDT.',
  MATIC: 'Polygon (formerly MATIC) is a layer-2 scaling solution for Ethereum, providing faster and cheaper transactions through sidechains and zero-knowledge rollups. It hosts a vast ecosystem of DeFi protocols, gaming dApps, and enterprise solutions.',
  DOT: 'Polkadot is a multi-chain protocol designed to connect different blockchains into a unified network, enabling seamless data and asset transfer. Its native token, DOT, is used for governance, staking, and parachain auctions.',
  LTC: 'Litecoin was created in 2011 as a faster and lighter alternative to Bitcoin, with shorter block times and a different hashing algorithm (Scrypt). It is often referred to as the silver to Bitcoin\'s gold and remains widely accepted for payments.',
  AVAX: 'Avalanche is a high-throughput, low-latency smart-contracts platform designed for DeFi and enterprise use. Its consensus mechanism, Avalanche consensus, enables sub-second finality and the ability to launch custom subnets with unique rule sets.',
  LINK: 'Chainlink is a decentralized oracle network that connects smart contracts to real-world data, such as price feeds, weather data, and event outcomes. Its native token, LINK, is used to pay node operators for retrieving and delivering data.',
  BCH: 'Bitcoin Cash is a fork of Bitcoin that increased the block size limit to allow more transactions per block, aiming to be a practical peer-to-peer electronic cash system. It emphasizes low fees and fast confirmations for everyday payments.',
};